# Generated by Django 2.0.3 on 2018-05-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='mobile/')),
                ('contend', models.CharField(max_length=2000)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
