# Generated by Django 2.0.5 on 2018-05-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemodel',
            name='contend',
            field=models.TextField(),
        ),
    ]
