# Generated by Django 2.0.5 on 2018-05-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_auto_20180530_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='img',
            field=models.ImageField(null=True, upload_to='mobile/', verbose_name='Ảnh:'),
        ),
    ]
