# Generated by Django 2.0.5 on 2018-05-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Bình luận:', 'verbose_name_plural': 'Bình luận:'},
        ),
    ]
