# Generated by Django 2.0.5 on 2018-05-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0003_auto_20180530_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='internet/', verbose_name='Ảnh:'),
        ),
    ]
